In [24]:
## Vincent Purcell
## Data Mining 2 - HW1 K Folds
## Some of code is modified from the code Professor Breitzman provided us.

In [25]:
import csv
import pandas as pd
import re
import numpy
from sklearn.model_selection import KFold
from sklearn.metrics import classification_report,confusion_matrix

In [26]:
def is_empty_or_blank(msg):
    return re.search("^\s*$", msg)

with open('water_potability.csv') as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    line_count = 0
    columns = []
    data = []
    for row in csv_reader:
        if line_count == 0:
            data_series = pd.Series(row)
            features = list(data_series)
            columns = row
            line_count += 1
        else:
            data_series = pd.Series(row)
            data_row = list(data_series)
            result = any([is_empty_or_blank(elem) for elem in data_row])
            if result == False:
                data.append([float(i) for i in data_row])

data = numpy.array(data)
X = data[:,0:9]
Y = data[:,9]

In [27]:
# Columns and example data row
print(columns)
print(data[0])

['ph', 'Hardness', 'Solids', 'Chloramines', 'Sulfate', 'Conductivity', 'Organic_carbon', 'Trihalomethanes', 'Turbidity', 'Potability']
[8.31676588e+00 2.14373394e+02 2.20184174e+04 8.05933238e+00
 3.56886136e+02 3.63266516e+02 1.84365245e+01 1.00341674e+02
 4.62877054e+00 0.00000000e+00]


In [28]:
kf = KFold(n_splits=5, random_state=35, shuffle=True)
kf

KFold(n_splits=5, random_state=35, shuffle=True)

In [29]:
for index, (train, test) in enumerate(kf.split(X), 1):
    
    print(f'Split {index}:\n')
    
    print(test)
    print('\n')

Split 1:

[   5   15   22   27   29   33   36   40   42   43   47   67   68   69
   73   74   76   81   87   94   99  101  110  116  119  131  133  134
  138  143  149  158  168  176  183  202  205  214  215  218  220  221
  223  224  227  230  233  238  239  242  253  261  262  268  269  278
  279  281  282  288  292  295  296  298  299  300  305  316  318  319
  323  327  334  335  336  337  344  347  348  351  357  360  364  367
  368  369  371  376  386  387  392  397  401  408  427  430  434  440
  442  444  449  454  460  464  473  474  479  486  489  493  510  513
  516  517  522  539  541  548  551  553  561  567  572  574  586  589
  591  597  600  613  614  615  620  629  644  645  652  658  678  679
  684  688  689  693  697  703  707  717  721  723  727  737  738  740
  742  750  755  756  757  762  764  771  779  786  788  789  790  791
  801  804  805  810  814  827  828  834  842  854  861  867  869  874
  885  893  897  898  899  903  907  912  916  918  919  924  934  

In [30]:
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

for index, (train, test) in enumerate(kf.split(X), 1):
    
    print(f'Split {index}:\n')
    
    X_train = X[train]
    X_test = X[test]
    y_train = Y[train]
    y_test = Y[test]
    
    scaler.fit(X_train)
    
    X_train = scaler.transform(X_train)
    X_test = scaler.transform(X_test)
    
    mlp = MLPClassifier(hidden_layer_sizes=(30,30,30,3), max_iter=2000)
    mlp.fit(X_train,y_train)
    predictions = mlp.predict(X_test)

    print(confusion_matrix(y_test, predictions))
    print(classification_report(y_test, predictions))
    
    print('\n')

Split 1:

[[187  57]
 [100  59]]
              precision    recall  f1-score   support

         0.0       0.65      0.77      0.70       244
         1.0       0.51      0.37      0.43       159

    accuracy                           0.61       403
   macro avg       0.58      0.57      0.57       403
weighted avg       0.60      0.61      0.60       403



Split 2:

[[153  91]
 [ 61  97]]
              precision    recall  f1-score   support

         0.0       0.71      0.63      0.67       244
         1.0       0.52      0.61      0.56       158

    accuracy                           0.62       402
   macro avg       0.62      0.62      0.61       402
weighted avg       0.64      0.62      0.63       402



Split 3:

[[166  71]
 [ 90  75]]
              precision    recall  f1-score   support

         0.0       0.65      0.70      0.67       237
         1.0       0.51      0.45      0.48       165

    accuracy                           0.60       402
   macro avg       0.58  